name: sito-savino
services:
  - name: web
    github:
      repo: MarcoVanzo/sito_savino
      branch: main
    build_command: composer install --optimize-autoloader --no-dev && npm install && npm run build-assets && php artisan migrate --force
    run_command: heroku-php-apache2 public/
    envs:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: ${APP_URL}
      - key: APP_KEY
        type: SECRET
        # Genera con: php artisan key:generate --show
        # Poi imposta come variabile segreta nel pannello DigitalOcean
      - key: PREVIEW_AUTH_USER
        type: SECRET
        # Imposta come variabile segreta nel pannello DigitalOcean
      - key: PREVIEW_AUTH_PASS
        type: SECRET
        # Imposta come variabile segreta nel pannello DigitalOcean
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${sito-savino-db.HOSTNAME}
      - key: DB_PORT
        value: ${sito-savino-db.PORT}
      - key: DB_DATABASE
        value: ${sito-savino-db.DATABASE}
      - key: DB_USERNAME
        value: ${sito-savino-db.USERNAME}
      - key: DB_PASSWORD
        value: ${sito-savino-db.PASSWORD}
      - key: FILESYSTEM_DISK
        value: s3
      - key: AWS_ACCESS_KEY_ID
        value: DO002PZMHRRDGTZYR674
      - key: AWS_SECRET_ACCESS_KEY
        value: dC+MMPAv0T93k/vq6NsBe8i1pB7tuMKRl+Z4WJaE7A4
      - key: AWS_DEFAULT_REGION
        value: fra1
      - key: AWS_BUCKET
        value: sito-savino-assets-2026
      - key: AWS_ENDPOINT
        value: https://fra1.digitaloceanspaces.com
      - key: LOG_CHANNEL
        value: daily
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_ENCRYPT
        value: "true"
databases:
  - name: sito-savino-db
    engine: MYSQL
    version: "8"
    production: true
    cluster_name: sito-savino-db
